# Generated by Django 3.1.7 on 2021-10-09 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(help_text='buy or sell order', max_length=3)),
                ('location', models.CharField(help_text='Enter the location of order', max_length=30)),
                ('item_id', models.CharField(help_text='Enter the UniqueName of item', max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Price of item')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
