# Generated by Django 3.1.7 on 2021-10-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20211010_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='location',
            field=models.CharField(choices=[('0', 'Thetford'), ('1', 'Martlock'), ('2', 'Bridgewatch'), ('3', 'Lymhurst'), ('4', 'Fort Sterling'), ('5', 'Caerleon')], default='3', help_text='Enter the location of order', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('b', 'Buy'), ('s', 'Sell')], help_text='Buy or Sell order', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='order_matching',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Finish'), ('2', 'Cancel')], default='0', help_text='Status of order', max_length=1),
        ),
    ]
