# Generated by Django 3.1.7 on 2021-10-12 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0005_auto_20211010_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Matching',
            new_name='OrderMatching',
        ),
    ]
