# Generated by Django 3.1.7 on 2021-10-12 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_auto_20211012_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermatching',
            old_name='order_id',
            new_name='order',
        ),
    ]
