# Generated by Django 3.1.7 on 2021-10-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20211012_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quality',
            field=models.CharField(choices=[('0', 'Normal'), ('1', 'Good'), ('2', 'Outstanding'), ('3', 'Excellent'), ('4', 'Masterpiece')], default='0', help_text='Enter the quality of item', max_length=1),
        ),
    ]
